### PR TITLE
Update linux scripts to support YARP 3.3.1

### PR DESCRIPTION
**Pull request by traversaro**
* Add bundle-3-3-1.sh configuration file
* Modify src/build_yarp.sh script to always download from an archive CMake 3.12, as it is required per the discussion in https://github.com/robotology/QA/issues/364 
* Modify src/build_yarp.sh to pass DEBIAN_FRONTEND=noninteractive to apt-get to avoid to have to manually configure tzdata

### CODE REVIEW

**Comment by drdanz** [comment]
I'm missing the `DEBIAN_FRONTEND` part in the patch, all I see is a comment :laughing:

**Comment by traversaro** [comment]
> I'm missing the `DEBIAN_FRONTEND` part in the patch, all I see is a comment laughing

Good point, it was actually:
~~~
   run_in_chroot build_chroot "DEBIAN_FRONTEND=noninteractive apt-get -y install $DEPENDENCIES_COMMON" || exit 1 
~~~
but probably I accidentally reverted the change.

**Comment by mbrunettini** [comment]
Unfortunately build on Ubuntu EOAN fails:

>[  3%] Building CXX object src/libYARP_os/src/CMakeFiles/YARP_os.dir/yarp/os/Carrier.cpp.o
In file included from /usr/include/ace/OS_NS_stropts.h:30,
                 from /usr/include/ace/IPC_SAP.inl:2,
                 from /usr/include/ace/IPC_SAP.h:87,
                 from /usr/include/ace/SOCK.h:22,
                 from /usr/include/ace/SOCK_IO.h:16,
                 from /usr/include/ace/SOCK_Stream.h:15,
                 from /usr/include/ace/SOCK_Acceptor.h:15,
                 from /tmp/yarp-3.3.1/src/libYARP_os/src/yarp/os/impl/TcpAcceptor.h:13,
                 from /tmp/yarp-3.3.1/src/libYARP_os/src/yarp/os/impl/TcpFace.h:17,
                 from /tmp/yarp-3.3.1/src/libYARP_os/src/yarp/os/Carrier.cpp:11:
/usr/include/ace/os_include/os_stropts.h:56:17: fatal error: stropts.h: No such file or directory
   56 | #  include /**/ <stropts.h>
      |                 ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/libYARP_os/src/CMakeFiles/YARP_os.dir/build.make:115: src/libYARP_os/src/CMakeFiles/YARP_os.dir/yarp/os/Carrier.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:582: src/libYARP_os/src/CMakeFiles/YARP_os.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
make: *** [Makefile:26: yarp_eoan_amd64.txt] Error 1

**Comment by traversaro** [comment]
I think this is https://github.com/robotology/yarp/issues/2125 . Personally I would just avoid producing packages for Ubuntu 19.10, but if we want to go forward I can provide a workaround also for this, but to be honest I do not think it is worth spending time on Ubuntu 19.10 and its broken system packages. 
cc @pattacini @drdanz

**Comment by mbrunettini** [comment]
skipping EOAN

**Comment by pattacini** [comment]
Fully agree to not support 19.10 👍

**Comment by mbrunettini** [comment]
packages for : 
- Debian Stretch
- Debian Buster
- Ubuntu Bionic 18.04
- Ubuntu Disco 19.04
are now available
I think we can close this

**Comment by drdanz** [comment]
:+1: for not supporting 19.10. I suggest to add a note about this in the announcement.
Let's just hope that 20.04 will be ok.

**Comment by traversaro** [comment]
>  Let's just hope that 20.04 will be ok.

I think a fix was made in Ubuntu packaging, and should be available in 20.04, see https://bugs.launchpad.net/ubuntu/+source/ace/+bug/1852425 .

**Pull request merged**
